apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-api
  labels:
    app: dog-api
    tier: backend
  namespace: k8s
spec:
  selector:
    matchLabels:
      app: dog-api
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: dog-api
        tier: backend
      namespace: k8s
    spec:
      containers:
        - name: dog-api
          image: dog-api
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dog-api
  labels:
    app: dog-api
    tier: backend
  namespace: k8s
spec:
  type: NodePort
  selector:
    app: dog-api
    tier: backend
  ports:
    - name: http
      protocol: TCP
      targetPort: 3000
      port: 80
